"""Write built-in ADF project templates (BUILD-008)."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "adf-templates"


def write(rel: str, content: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def main() -> None:
    write(
        "foundation/template.yaml",
        """schema_version: "1.0"
metadata:
  name: foundation
  version: 0.8.0
  description: Base ADF project layout driven by template metadata
  author: YoghaLabs
  tags: [foundation, builtin]
  build: BUILD-008
variables:
  project_name: adf-project
  author: YoghaLabs
  version: 0.1.0-alpha
dependencies: []
capabilities:
  - scaffold
  - documentation
  - adf-operating-set
  - bootstrap
outputs:
  - README.md
  - VERSION
  - CHANGELOG.md
  - ROADMAP.md
  - .adf/PROJECT_STATE.md
  - .adf/PROJECT_MANIFEST.md
  - .adf/CURRENT_TASK.md
  - .adf/MEMORY.md
  - .adf/SESSION.md
  - .adf/TODOS.md
  - .adf/HANDOFF.md
  - .adf/BOOTSTRAP.md
  - .adf/AI_CONTRACT.md
  - .adf/QUICK_CONTEXT.md
  - prompts/README.md
  - bootstrap/README.md
  - bootstrap/BOOT_SEQUENCE.md
  - bootstrap/BUILD_CONTRACT.md
  - adf-core/README.md
permissions:
  - write-files
inherits: null
plugin_compatibility:
  - template
  - generator
  - bootstrap
""",
    )

    files = {
        "foundation/files/README.md": (
            "# {{project_name}}\n\nGenerated by the ADF Bootstrap Generator.\n\n"
            "Author: {{author}}\nVersion: {{version}}\n\n"
            "Documentation is SSOT. See `.adf/` for operating state.\n"
        ),
        "foundation/files/VERSION": (
            "ADF\n\nVersion:\n{{version}}\n\nCurrent Build:\nBUILD-001\n\nBranch:\ndevelop\n"
        ),
        "foundation/files/CHANGELOG.md": (
            "# Changelog\n\n**Version:** `{{version}}`\n\n## [Unreleased]\n\n"
            "### Added\n- Initial project scaffold from ADF generator\n"
        ),
        "foundation/files/ROADMAP.md": (
            "# Roadmap\n\n| Build | Focus | Status |\n|-------|--------|--------|\n"
            "| BUILD-001 | Repository Foundation | ✅ |\n"
        ),
        "foundation/files/.adf/PROJECT_STATE.md": (
            "# Project State\n\n| Field | Value |\n|-------|-------|\n"
            "| Project | `{{project_name}}` |\n| Version | `{{version}}` |\n"
            "| Author | `{{author}}` |\n| Build | `BUILD-001` |\n| Status | `Bootstrapped` |\n"
        ),
        "foundation/files/.adf/PROJECT_MANIFEST.md": (
            "# Project Manifest\n\n| Field | Value |\n|-------|-------|\n"
            "| Name | `{{project_name}}` |\n| Version | `{{version}}` |\n"
            "| Author | `{{author}}` |\n| Generator | ADF BUILD-008 |\n"
        ),
        "foundation/files/.adf/CURRENT_TASK.md": (
            "# Current Task\n\nComplete BUILD-001 orientation: read README, VERSION, and `.adf` SSOT.\n"
        ),
        "foundation/files/.adf/MEMORY.md": (
            "# Memory\n\nProject `{{project_name}}` was generated by the ADF Bootstrap Generator.\n"
        ),
        "foundation/files/.adf/SESSION.md": (
            "# Session\n\nInitial bootstrap session for `{{project_name}}`.\n"
        ),
        "foundation/files/.adf/TODOS.md": (
            "# TODOs\n\n- [ ] Review generated layout\n- [ ] Fill project-specific docs\n"
        ),
        "foundation/files/.adf/HANDOFF.md": (
            "# Handoff\n\nHand off `{{project_name}}` by updating PROJECT_STATE, CURRENT_TASK, and SESSION.\n"
        ),
        "foundation/files/.adf/BOOTSTRAP.md": (
            "# Bootstrap\n\nFollow `bootstrap/BOOT_SEQUENCE.md` to enter a valid working state.\n"
        ),
        "foundation/files/.adf/AI_CONTRACT.md": (
            "# AI Contract\n\n- Respect locked top-level architecture\n"
            "- Documentation remains SSOT\n- No placeholder files\n- Cumulative builds only\n"
        ),
        "foundation/files/.adf/QUICK_CONTEXT.md": (
            "# Quick Context\n\n- Project: {{project_name}}\n- Version: {{version}}\n- Author: {{author}}\n"
        ),
        "foundation/files/prompts/README.md": "# Prompts\n\nPrompt library seed for `{{project_name}}`.\n",
        "foundation/files/prompts/build.md": (
            "# Prompt — Build\n\n```text\nOperate within the active BUILD boundary. "
            "Update SSOT after changes.\n```\n"
        ),
        "foundation/files/prompts/resume.md": (
            "# Prompt — Resume\n\n```text\nRead QUICK_CONTEXT, PROJECT_STATE, CURRENT_TASK, then continue.\n```\n"
        ),
        "foundation/files/bootstrap/README.md": "# Bootstrap\n\nBootstrap contracts for `{{project_name}}`.\n",
        "foundation/files/bootstrap/BOOT_SEQUENCE.md": (
            "# Boot Sequence\n\n1. Read VERSION\n2. Read `.adf/PROJECT_STATE.md`\n3. Read CURRENT_TASK\n"
        ),
        "foundation/files/bootstrap/BUILD_CONTRACT.md": (
            "# Build Contract\n\nA BUILD is complete only when acceptance criteria and docs are updated.\n"
        ),
        "foundation/files/adf-core/README.md": (
            "# adf-core\n\nRuntime package seed for `{{project_name}}`. "
            "Depend on upstream ADF `adf-core` as needed.\n"
        ),
    }
    for rel, content in files.items():
        write(rel, content)

    for name in (
        ".adf",
        "adf-core",
        "adf-studio",
        "adf-docs",
        "adf-examples",
        "adf-templates",
        "bootstrap",
        "prompts",
        "testing",
        "tools",
        "release",
    ):
        write(f"foundation/files/{name}/.gitkeep", "")

    write(
        "generic/template.yaml",
        """schema_version: "1.0"
metadata:
  name: generic
  version: 0.8.0
  description: Generic ADF project (inherits foundation)
  author: YoghaLabs
  tags: [generic, builtin]
  build: BUILD-008
variables:
  project_name: generic-project
  author: YoghaLabs
  version: 0.1.0-alpha
capabilities: [scaffold, documentation, adf-operating-set]
outputs: [README.md, VERSION, .adf/PROJECT_STATE.md]
permissions: [write-files]
inherits: foundation
plugin_compatibility: [template, generator, bootstrap]
""",
    )
    write("generic/files/docs/OVERVIEW.md", "# Overview\n\nGeneric ADF project `{{project_name}}`.\n")

    write(
        "python/template.yaml",
        """schema_version: "1.0"
metadata:
  name: python
  version: 0.8.0
  description: Python ADF project
  author: YoghaLabs
  tags: [python, builtin]
  build: BUILD-008
variables:
  project_name: python-project
  author: YoghaLabs
  version: 0.1.0-alpha
  python_requires: ">=3.10"
capabilities: [scaffold, python]
outputs: [pyproject.toml, src/{{project_name}}/__init__.py]
permissions: [write-files]
inherits: generic
plugin_compatibility: [template, generator]
""",
    )
    write(
        "python/files/pyproject.toml",
        """[project]
name = "{{project_name}}"
version = "{{version}}"
description = "ADF-generated Python project"
requires-python = "{{python_requires}}"
authors = [{ name = "{{author}}" }]
""",
    )
    write(
        "python/files/src/{{project_name}}/__init__.py",
        '"""{{project_name}} package."""\n\n__version__ = "{{version}}"\n',
    )

    write(
        "fastapi/template.yaml",
        """schema_version: "1.0"
metadata:
  name: fastapi
  version: 0.8.0
  description: FastAPI ADF project
  author: YoghaLabs
  tags: [python, fastapi, builtin]
  build: BUILD-008
variables:
  project_name: fastapi-project
  author: YoghaLabs
  version: 0.1.0-alpha
capabilities: [scaffold, python, fastapi]
outputs: [app/main.py, requirements.txt]
permissions: [write-files]
inherits: python
plugin_compatibility: [template, generator]
""",
    )
    write(
        "fastapi/files/app/main.py",
        'from fastapi import FastAPI\n\n'
        'app = FastAPI(title="{{project_name}}", version="{{version}}")\n\n\n'
        '@app.get("/health")\n'
        "def health() -> dict[str, str]:\n"
        '    return {"status": "ok", "service": "{{project_name}}"}\n',
    )
    write("fastapi/files/requirements.txt", "fastapi>=0.110\nuvicorn>=0.27\n")

    write(
        "laravel/template.yaml",
        """schema_version: "1.0"
metadata:
  name: laravel
  version: 0.8.0
  description: Laravel-oriented ADF project seed
  author: YoghaLabs
  tags: [php, laravel, builtin]
  build: BUILD-008
variables:
  project_name: laravel-project
  author: YoghaLabs
  version: 0.1.0-alpha
capabilities: [scaffold, laravel]
outputs: [composer.json, README.md]
permissions: [write-files]
inherits: generic
plugin_compatibility: [template, generator]
""",
    )
    write(
        "laravel/files/composer.json",
        """{
  "name": "adf/{{project_name}}",
  "description": "ADF-generated Laravel seed for {{project_name}}",
  "type": "project",
  "require": {
    "php": "^8.2",
    "laravel/framework": "^11.0"
  }
}
""",
    )

    write(
        "nextjs/template.yaml",
        """schema_version: "1.0"
metadata:
  name: nextjs
  version: 0.8.0
  description: Next.js ADF project seed
  author: YoghaLabs
  tags: [javascript, nextjs, builtin]
  build: BUILD-008
variables:
  project_name: nextjs-project
  author: YoghaLabs
  version: 0.1.0-alpha
capabilities: [scaffold, nextjs]
outputs: [package.json, app/page.tsx]
permissions: [write-files]
inherits: generic
plugin_compatibility: [template, generator]
""",
    )
    write(
        "nextjs/files/package.json",
        """{
  "name": "{{project_name}}",
  "version": "{{version}}",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  }
}
""",
    )
    write(
        "nextjs/files/app/page.tsx",
        "export default function Home() {\n  return <main><h1>{{project_name}}</h1></main>;\n}\n",
    )

    print(f"wrote templates under {ROOT}")
    print("count", sum(1 for _ in ROOT.rglob("*") if _.is_file()))


if __name__ == "__main__":
    main()
