import { studioSdk } from "@/sdk";

/** Service adapters for features — thin SDK wrappers for UI modules. */
export const studioServices = {
  runtime: () => studioSdk.runtime,
  marketplace: () => studioSdk.marketplace,
  packages: () => studioSdk.packages,
  registry: () => studioSdk.registry,
  release: () => studioSdk.release,
  workspace: () => studioSdk.workspace,
  projects: () => studioSdk.projects,
  sessions: () => studioSdk.sessions,
  search: () => studioSdk.search,
  activity: () => studioSdk.activity,
  knowledge: () => studioSdk.knowledge,
  dependency: () => studioSdk.dependency,
  graph: () => studioSdk.graph,
  visualization: () => studioSdk.visualization,
  runtimeDashboard: () => studioSdk.runtimeDashboard,
  metrics: () => studioSdk.metrics,
  logs: () => studioSdk.logs,
  diagnostics: () => studioSdk.diagnostics,
  timeline: () => studioSdk.timeline,
  participants: () => studioSdk.participants,
  collaboration: () => studioSdk.collaboration,
  presence: () => studioSdk.presence,
  reviews: () => studioSdk.reviews,
  notifications: () => studioSdk.notifications,
  assignments: () => studioSdk.assignments,
};
