"""Scaffold locked ADF folder layout and seed documentation."""

from __future__ import annotations

from pathlib import Path

from generator.filesystem import FileSystem
from generator.output import GenerationOutput
from generator.writer import Writer
from runtime.constants import LOCKED_TOP_LEVEL


class Scaffolder:
    """Create locked top-level folders and baseline docs for a new project."""

    LOCKED = LOCKED_TOP_LEVEL

    def __init__(self, writer: Writer, fs: FileSystem | None = None) -> None:
        """Create a scaffolder bound to a writer."""
        self.writer = writer
        self.fs = fs or writer.fs
        self.output = writer.output

    def scaffold_folders(self, root: Path) -> list[Path]:
        """Create locked top-level directories under ``root``."""
        created: list[Path] = []
        for name in self.LOCKED:
            path = self.fs.ensure_dir(root / name)
            self.output.record_folder(path)
            created.append(path)
        self.output.progress(f"Scaffolded {len(created)} locked folders")
        return created

    def scaffold_root_docs(self, root: Path, *, project_name: str, version: str) -> None:
        """Write minimal root governance files if missing or overwrite allowed."""
        readme = (
            f"# {project_name}\n\n"
            "Generated by the ADF Bootstrap Generator (BUILD-008).\n\n"
            "Documentation is the source of truth. See `.adf/` for operating state.\n"
        )
        changelog = (
            f"# Changelog\n\n"
            f"**Version:** `{version}`\n\n"
            "## [Unreleased]\n\n"
            "### Added\n"
            "- Initial project scaffold from ADF generator\n"
        )
        roadmap = (
            "# Roadmap\n\n"
            "| Build | Focus | Status |\n"
            "|-------|--------|--------|\n"
            "| BUILD-001 | Repository Foundation | ✅ |\n"
        )
        self.writer.write_text(root / "README.md", readme)
        self.writer.write_text(root / "CHANGELOG.md", changelog)
        self.writer.write_text(root / "ROADMAP.md", roadmap)
        self.writer.write_text(
            root / "VERSION",
            (
                "ADF\n\n"
                f"Version:\n{version}\n\n"
                "Current Build:\nBUILD-001\n\n"
                "Branch:\ndevelop\n"
            ),
        )
        self.output.progress("Wrote root governance docs")

    def scaffold_adf(self, root: Path, *, project_name: str, version: str) -> None:
        """Generate a minimal `.adf` operating set."""
        adf = root / ".adf"
        self.fs.ensure_dir(adf)
        files = {
            "PROJECT_STATE.md": (
                "# Project State\n\n"
                f"| Field | Value |\n|-------|-------|\n"
                f"| Project | `{project_name}` |\n"
                f"| Version | `{version}` |\n"
                "| Build | `BUILD-001` |\n"
                "| Status | `Bootstrapped` |\n"
            ),
            "QUICK_CONTEXT.md": (
                "# Quick Context\n\n"
                f"- Project: {project_name}\n"
                f"- Version: {version}\n"
                "- Generated by ADF Bootstrap Generator\n"
            ),
            "CURRENT_TASK.md": (
                "# Current Task\n\n"
                "Complete BUILD-001 orientation: read README, VERSION, and `.adf` SSOT.\n"
            ),
            "AI_CONTRACT.md": (
                "# AI Contract\n\n"
                "- Respect locked top-level architecture\n"
                "- Documentation remains SSOT\n"
                "- No placeholder files\n"
                "- Cumulative builds only\n"
            ),
            "MEMORY.md": (
                "# Memory\n\n"
                f"Project `{project_name}` was generated by ADF BUILD-008 generator.\n"
            ),
            "TODOS.md": (
                "# TODOs\n\n"
                "- [ ] Review generated layout\n"
                "- [ ] Fill project-specific docs\n"
            ),
            "SESSION.md": (
                "# Session\n\n"
                "Initial bootstrap session. Run doctor/boot after installing adf-core.\n"
            ),
        }
        for name, content in files.items():
            self.writer.write_text(adf / name, content)
        self.output.progress("Generated .adf operating set")

    def scaffold_prompts(self, root: Path) -> None:
        """Generate a minimal prompts library."""
        prompts = root / "prompts"
        self.fs.ensure_dir(prompts)
        self.writer.write_text(
            prompts / "README.md",
            "# Prompts\n\nPrompt library seed generated by ADF.\n",
        )
        self.writer.write_text(
            prompts / "build.md",
            "# Prompt — Build\n\n```text\nOperate within the active BUILD boundary. Update SSOT after changes.\n```\n",
        )
        self.writer.write_text(
            prompts / "resume.md",
            "# Prompt — Resume\n\n```text\nRead QUICK_CONTEXT, PROJECT_STATE, CURRENT_TASK, then continue.\n```\n",
        )
        self.output.progress("Generated prompts seed")

    def scaffold_bootstrap(self, root: Path) -> None:
        """Generate bootstrap pack stubs."""
        boot = root / "bootstrap"
        self.fs.ensure_dir(boot)
        self.writer.write_text(
            boot / "README.md",
            "# Bootstrap\n\nBootstrap contracts for this ADF project.\n",
        )
        self.writer.write_text(
            boot / "BOOT_SEQUENCE.md",
            "# Boot Sequence\n\n1. Read VERSION\n2. Read `.adf/PROJECT_STATE.md`\n3. Read CURRENT_TASK\n",
        )
        self.writer.write_text(
            boot / "BUILD_CONTRACT.md",
            "# Build Contract\n\nA BUILD is complete only when acceptance criteria and docs are updated.\n",
        )
        self.output.progress("Generated bootstrap docs")

    def scaffold_runtime_config(self, root: Path) -> None:
        """Generate a minimal runtime configuration note under adf-core."""
        core = root / "adf-core"
        self.fs.ensure_dir(core)
        self.writer.write_text(
            core / "README.md",
            "# adf-core\n\nRuntime package placeholder for this generated project. "
            "Copy or depend on upstream ADF `adf-core` as needed.\n",
        )
        self.output.progress("Generated runtime configuration seed")
